package pe2;

/*
 * Each new term in the Fibonacci sequence is generated by
 * adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 * 
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 * 
 * By considering the terms in the Fibonacci sequence whose
 * values do not exceed four million, find the sum of the
 * even-valued terms.
 */

public class PE2 {
	public static void main(String[] args) {
		int total = 0, minustwo = 0, minusone = 1, current = 2;
		while (current <= 4000000) {
			total += current;
			minustwo = minusone;
			minusone = current;
			current = minustwo + minusone;// this one is odd
			minustwo = minusone;
			minusone = current;
			current = minustwo + minusone;// so is this one
			minustwo = minusone;
			minusone = current;
			current = minustwo + minusone;
		}
		System.out.println(total);
	}
}
